SaRaEcommerce/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NLog;
using SaRaEcommerce.Dal;
using SaRaEcommerce.Models;
using SaRaEcommerce.Utility;
using SaRaEcommerce.ViewModel;

namespace SaRaEcommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly HomeModel _objHomeModel = new HomeModel();
        private readonly HomeDal _objHomeDal = new HomeDal();

        //[OutputCache(Duration = 60, VaryByParam = "none", Location = System.Web.UI.OutputCacheLocation.Server)]
        public async Task<ActionResult> Index()
        {
            _objHomeModel.HomepageSliders = await _objHomeDal.GetHomepageSlider();
            _objHomeModel.HomepageBanners = await _objHomeDal.GetHomepageBanner();
            _objHomeModel.HomepageOffers = await _objHomeDal.GetHomepageOffers();

            var popupImage = await _objHomeDal.GetHomePagePopup();
            ViewBag.Popup = popupImage;

            return View(_objHomeModel);
        }

        [HttpGet]
        public async Task<ActionResult> UpcomingProduct()
        {
            var objUpcomingProduct = await _objHomeDal.GetUpcomingProduct();

            return PartialView("HomePagePartial/_UpcomingProductPartial", objUpcomingProduct);
        }

        public async Task<ActionResult> PlacePreOrder(int productId, string customerId)
        {
            string message = "";
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            if (user != null)
            {
                if (customerId == user.Id && productId != 0)
                 message = await _objHomeDal.PlacePreOrder(productId, customerId);

                new Thread(() =>
                {
                    string body = "Your Pre-Order Successfully Placed, you will get another mail for confirmation and delivery date, for more information please contact with us ( +88 01885 998899).";

                    UtilityClass.SendEmail(user.Email, "SaRa Lifestyle - Pre-Order Status", body, null);
                }).Start();
            }
            return Json(message, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [OutputCache(Duration = 60)]
        public async Task<ActionResult> OccasionalProduct()
        {
            var objOccasionalProduct = await _objHomeDal.GetOccasionalProducts();

            var occasionalSlider = await _objHomeDal.GetOccasionalSlider();
            ViewBag.OccasionalSlider = occasionalSlider;

            return PartialView("HomePagePartial/_OccasionalProductPartial", objOccasionalProduct);
        }

        [HttpGet]
        [OutputCache(Duration = 60)]
        public async Task<ActionResult> NewArrivals()
        {
            var objNewArrivalsProduct = await _objHomeDal.GetNewArrivalsProduct();

            return PartialView("HomePagePartial/_NewArrivalsPartial", objNewArrivalsProduct);
        }

        [HttpGet]
        [OutputCache(Duration = 60)]
        public async Task<ActionResult> TrendingProducts()
        {
            var objTrendingProduct = await _objHomeDal.GetTrendingProducts();

            return PartialView("HomePagePartial/_TrendingProductsPartial", objTrendingProduct);
        }

        [HttpGet]
        [OutputCache(Duration = 60)]
        public async Task<ActionResult> PromotionalProducts()
        {
            var objPromotionalProducts = await _objHomeDal.GetPromotionalProducts();

            return PartialView("HomePagePartial/_PromotionalProductPartial", objPromotionalProducts);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"] as string;
            }
            ModelState.Clear();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(CustomerContact objContact)
        {
            string message;

            if (!ModelState.IsValid)
            {
                message = "Invalid";
                return RedirectToAction("Contact", "Home", new {message });
            }
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            if (user != null)
            {
                objContact.CustomerId = user.Id;
            }

            message = await _objHomeDal.SaveCustomerMessage(objContact);

            new Thread(() =>
            {
                string body = "Thank you for your response, We will contact with you soon.";

                UtilityClass.SendEmail(objContact.CustomerEmail, "SaRa Life Style", body, null);
            }).Start();

            var emailList = new List<string> { "ecom@saralifestyle.com.bd" };

            foreach (var email in emailList)
            {
                new Thread(() =>
                {
                    string body = objContact.Message;

                    UtilityClass.SendEmail(email, objContact.CustomerName + " (" + objContact.CustomerEmail + ")", body, null);
                }).Start();
            }

            TempData["message"] = message;

            return RedirectToAction("Contact", "Home");
        }


        [ChildActionOnly]
        [OutputCache(Duration = 60)]
        public async Task<ActionResult> Menu()
        {
            var menuMains = await _objHomeDal.GetMenuMain();

            foreach (var menuMain in menuMains)
            {
                menuMain.MenuSubs = await _objHomeDal.GetMenuSub(menuMain.MenuMainId);

                foreach (var menuSub in menuMain.MenuSubs)
                {
                    menuSub.MenuSubSubs = await _objHomeDal.GetMenuSubSub(menuMain.MenuMainId, menuSub.MenuSubId);
                }
            }

            return PartialView("HomePagePartial/_MenuePartial", menuMains);
        }

        public ActionResult News()
        {
            return View();
        }

        public ActionResult Blog()
        {
            return View();
        }

        public ActionResult BlogItem()
        {
            return View();
        }
    }
}

SaRaEcommerce/Controllers/MagazineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaRaEcommerce.Controllers
{
    public class MagazineController : Controller
    {
        // GET: Magazine
        public ActionResult MagazineOne()
        {
            return View();
        }
        public ActionResult MagazineTwo()
        {
            return View();
        }
        public ActionResult MagazineThree()
        {
            return View();
        }
        public ActionResult MagazineFour()
        {
            return View();
        }
        public ActionResult MagazineFive()
        {
            return View();
        }
        public ActionResult MagazineSix()
        {
            return View();
        }

    }
}

SaRaEcommerce/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SaRaEcommerce/Views/Home/Contact.cshtml
@model SaRaEcommerce.ViewModel.CustomerContact
@{
    ViewBag.Title = "Contact";
}

<div class="row ">
    <div class="col-md-12">
        <ul class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
            <li><a href="">Pages</a></li>
            <li class="active">Contact</li>
        </ul>
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40 contact-page">
            <!-- BEGIN SIDEBAR -->
            <div class="col-md-3 col-sm-3 col-xs-12 contact-address">
                <h2 class="our-contacts">Our Contacts</h2>
                <strong><a href="#corporate_office" class="outlet_address">Corporate Office:</a></strong>
                <address>
                    <i class="fa fa-map-marker" aria-hidden="true"></i> Address: SaRa Lifestyle Ltd.<br />
                    Avenue #02, Road #14, House No #966, <br />
                    Mirpur DOHS, Dhaka-1216, Bangladesh.<br /><br />
                    <i class="fa fa-phone" aria-hidden="true"></i> &nbsp;Mobile: + 88-01885-998899<br />
                </address>


                <h2 class="our-contacts">Outlet Address</h2>
                <strong><a href="#mirpur" class="outlet_address">Mirpur Outlet:</a></strong>
                <address>
                    Location: Plot -10, Block - Ka, Road -1, Section -6 ,Mirpur, Dhaka -1216 (Opposite of gate-5 at Sher-e-Bangla National Cricket Stadium). <br />
                    Contact number: 01760888101, 01735089990.<br />
                    <strong>Open: 10:00 AM to 10:00 PM (Everyday)</strong>

                </address>

                <strong><a href="#bashundhara_city" class="outlet_address">Bashundhara City Outlet:</a></strong>
                <address>
                    Location: Level-1, Block- A, Shop No- 40,54 &55 (West Gate/ Besides Mostofa Mart). Bashundhara City Shopping Complex.<br />
                    Contact number: 01886995554. <br />
                    <strong>Open: 10:00 AM to 10:00 PM(Only Friday) & others day Open: 10:00 AM to 09:00 PM (Closed on Tuesday) </strong>
                    <br />
                </address>
                
                <strong><a href="#mohammadpur_outlet" class="outlet_address">Mohammadpur Outlet:</a></strong>
                <address>
                    Location: House-19B/4C & 19B/4D, Block -F, Ring Road, Mohammadpur, Dhaka-1207.  <br />
                    Contact number: 01870728585.<br />
                    <strong>Open: 10:00 AM to 10:00 PM.</strong><br />
                </address>
                
                <strong><a href="#uttara_outlet" class="outlet_address">Uttara Outlet:</a></strong>
                <address>
                    Location: House no - 11, Sector - 09 Sonargaon Jonopoth Road, Uttara, Dhaka -1230. <br />
                    Contact number: 01886995553.<br />
                    <strong>Open: 10:00 AM to 10:00 PM.</strong>
                </address>
                
                <strong><a href="#baridhara_outlet" class="outlet_address">Baridhara Jblock Outlet:</a></strong>
                <address>
                    Location: House - 34 & 07, Road - 7, J Block, Pragati Sarani, Baridhara, Dhaka -1212.<br />
                    Contact number: 01870728485.<br />
                    <strong>Open: 10:00 AM to 10:00 PM.</strong>
                    <br />
                </address>


            

              


                <address>
                    <strong>Email:</strong><br>
                    @*<a href="mailto:info@saralifestylebd.com.com"> info@saralifestylebd.com.bd</a><br>*@
                    <a href="mailto:ecom@saralifestyle.com.com">ecom@saralifestyle.com.bd</a><br>
                    <a href="mailto:support@saralifestyle.com.com">support@saralifestyle.com.bd</a>
                </address>

                <ul class="social-icons margin-bottom-10">
                    <li><a class="facebook" data-original-title="facebook" href="https://www.facebook.com/saralifestyle.bd/"></a></li>
                    <li><a class="linkedin" data-original-title="linkedin" href="https://www.linkedin.com/company/saralifestyle/?viewAsMember=true"></a></li>
                    <li><a class="youtube" data-original-title="youtube" href="https://www.youtube.com/channel/UCGy5oteVoLcCdbC5fBGBmIw?reload=9"></a></li>
                    <li><a class="instagram" data-original-title="instagram" href="https://www.instagram.com/saralifestyle.bd/"></a></li>
                </ul>
            </div>
            <!-- END SIDEBAR -->
            <!-- BEGIN CONTENT -->
            <div class="col-md-9 col-sm-9 col-xs-12">
                <h2 class="contact-map">Site Map</h2>
                <div class="content-page">

                    <div id="corporate_office" class="gmaps margin-bottom-40" style="height: 400px;">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1824.7026824215748!2d90.36488075446742!3d23.839735239272457!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c142f7a48019%3A0xd3abc1bfb60c6a77!2sSaRa+Lifestyle+Ltd.!5e0!3m2!1sen!2sbd!4v1552538314378" width="100%" height="400" frameborder="1" style="border:1px solid #ddd;" allowfullscreen></iframe>
                    </div>

                    <div id="bashundhara_city" class="gmaps margin-bottom-40" style="height: 400px;">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1825.9451041512818!2d90.38993435084642!3d23.75129429095471!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5c2b8755e4327004!2sBashundhara+City+Shopping+Complex!5e0!3m2!1sen!2sbd!4v1552732811484" width="100%" height="400" frameborder="1" style="border:1px solid #ddd;" allowfullscreen></iframe>
                    </div>


                    <div id="mirpur" class="gmaps margin-bottom-40" style="height: 400px;">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3650.342261834782!2d90.36227316543219!3d23.8064253925498!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x13d2c6d4952332b2!2sSaRa+Lifestyle+Ltd.+(Mirpur)!5e0!3m2!1sen!2sbd!4v1552732394569" width="100%" height="400" frameborder="1" style="border:1px solid #ddd;" allowfullscreen></iframe>
                    </div>

                    <div id="uttara_outlet" class="gmaps margin-bottom-40" style="height: 400px;">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3648.4173359919923!2d90.39455851498373!3d23.874815584528196!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c43c3a4e9ced%3A0xb032c4b6ec0c1bf9!2sUttara+Adhunik+Medical+College+And+Hospital!5e0!3m2!1sen!2sbd!4v1558766436670!5m2!1sen!2sbd" width="100%" height="400" frameborder="1" style="border:1px solid #ddd;" allowfullscreen></iframe>
                    </div>

                    <div id="mohammadpur_outlet" class="gmaps margin-bottom-40" style="height: 400px;">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d7303.079021826124!2d90.35843252656275!3d23.763795157536045!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sHouse%23%2019B.4C%20%26%204D%2CBlock%20F%20Shamoly%20Ring%20road.%20Mohammadpur.%20Dhaka%201207!5e0!3m2!1sen!2sbd!4v1569585017434!5m2!1sen!2sbd" width="100%" height="400" frameborder="1" style="border:1px solid #ddd;" allowfullscreen></iframe>
                    </div>
                    
                    <div id="baridhara_outlet" class="gmaps margin-bottom-40" style="height: 400px;">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7300.9378790502715!2d90.41704412683981!3d23.801918204581213!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c7ae2e36518f%3A0xa99fbb70a63e1639!2sBaridhara%2C%20Dhaka%201212!5e0!3m2!1sen!2sbd!4v1574683555425!5m2!1sen!2sbd" width="100%" height="400" frameborder="1" style="border:1px solid #ddd;" allowfullscreen></iframe>

                    </div>


                    <div class="row" style="margin-bottom:20px;" id="mirpur">
                        <div class="col-md-4">
                            <img src="~/plugins/pages/img/shop/1.jpg" class="img-responsive" alt="SaRa Lifestyle Ltd" style="border:1px solid #ddd;padding:5px" />
                        </div>

                        <div class="col-md-4">
                            <img src="~/plugins/pages/img/shop/2.jpg" class="img-responsive" alt="SaRa Lifestyle Ltd" style="border:1px solid #ddd;padding:5px" />
                        </div>

                        <div class="col-md-4">
                            <img src="~/plugins/pages/img/shop/3.jpg" class="img-responsive" alt="SaRa Lifestyle Ltd" style="border:1px solid #ddd;padding:5px" />
                        </div>
                    </div>

                    <div class="gmaps row" style="margin-bottom:20px;" id="bashundhara_city">
                        <div class="col-md-4">
                            <img src="~/plugins/pages/img/shop/3.jpg" class="img-responsive" alt="SaRa Lifestyle Ltd" style="border:1px solid #ddd;padding:5px" />
                        </div>

                        <div class="col-md-4">
                            <img src="~/plugins/pages/img/shop/2.jpg" class="img-responsive" alt="SaRa Lifestyle Ltd" style="border:1px solid #ddd;padding:5px" />
                        </div>

                        <div class="col-md-4">
                            <img src="~/plugins/pages/img/shop/1.jpg" class="img-responsive" alt="SaRa Lifestyle Ltd" style="border:1px solid #ddd;padding:5px" />
                        </div>
                    </div>





                    <h2>Contact Us</h2>
                    <p class="text-justify" style="font-weight:500">Thanks for your interest in SaRa Lifestyle. Please use this form if you have any questions about our products and we will get back with you very soon. Our support team makes sure that you get the best advice and guidance regarding whatever queries you have. </p>

                    <!-- BEGIN FORM-->
                    @using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { @class = "default-form", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            @Html.LabelFor(c => c.CustomerName)
                            <span class="require" style="color:red;">*</span>
                            @Html.TextBoxFor(c => c.CustomerName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(c => c.CustomerName)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(c => c.CustomerEmail)
                            <span class="require" style="color:red;">*</span>
                            @Html.TextBoxFor(c => c.CustomerEmail, new { @class = "form-control" })
                            @Html.ValidationMessageFor(c => c.CustomerEmail)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(c => c.Message)
                            <span class="require" style="color:red;">*</span>
                            @Html.TextAreaFor(c => c.Message, new { @class = "form-control", @rows = 8 })
                            @Html.ValidationMessageFor(c => c.Message)
                        </div>
                        <div class="padding-top-20">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    }
                    <!-- END FORM-->






                </div>



            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function() {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "positionClass": "toast-top-center",
                "onclick": null,
                "showDuration": "1000",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }

            @if (ViewBag.Message != null)
            {
                <text>
                    var vMessage = '@ViewBag.Message';
                    toastr.info(vMessage, 'Information!');
                </text>
            }

    });



    $('.gmaps:not(:first)').hide();
        $('.outlet_address').click(function (event) {
            event.preventDefault();
            var content = $(this).attr('href');
            $(this).parent().addClass('active');
            $(this).parent().siblings().removeClass('active');
            $(content).show();
            $(content).siblings('.gmaps').hide();
    });

    </script>
}

SaRaEcommerce/Views/Home/News.cshtml
@{
    ViewBag.Title = "News";
}


<div class="row margin-bottom-20 news-events" style="min-height:500px !important;">

    <!-- BEGIN SIDEBAR -->
    <div class="col-md-3 col-sm-5">
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">LATEST NEWS FEED</div>
            <div class="list-group list-group-flush news-menu">
                <a href="#page-one" class="list-group-item list-group-item-action bg-light"><i class="fa fa-angle-right"></i> &nbsp; News Card</a>
            </div>
        </div>
    </div>
    <!-- END SIDEBAR -->

    <div class="col-md-9 col-sm-7">
        <div class="news-content-page" id="page-one">
            <!-- BEGIN CONTENT -->
            <h2 class="news-feed" style="margin-top:-5px !important;">MAGAZINES</h2>
            <hr />
            <div class="row margin-bottom-20 news-event-content">
                <div class="col-md-12 col-xs-12">
                    <div class="demo-gallery">
                        <ul class="list-unstyled row">

                            <li class="col-xs-6 col-sm-6 col-md-2">
                                <a href="@Url.Action("MagazineOne", "Magazine")">
                                    <img class="img-responsive" src="~/plugins/pages/img/news/4.jpg" alt="sara starts its journey in dhaka" />
                                    <div class="demo-gallery-poster">
                                        <img src="/plugins/pages/img/news/zoom.png" class="img-responsive hidden-xs" alt="sara starts its journey in dhaka" />
                                    </div>
                                </a>
                            </li>

                            <li class="col-xs-6 col-sm-6 col-md-2">
                                <a href="@Url.Action("MagazineTwo", "Magazine")">
                                    <img class="img-responsive" src="~/plugins/pages/img/news/1.jpg" alt="sara starts its journey in dhaka" />
                                    <div class="demo-gallery-poster">
                                        <img src="/plugins/pages/img/news/zoom.png" class="img-responsive hidden-xs" alt="sara starts its journey in dhaka" />
                                    </div>
                                </a>
                            </li>

                            <li class="col-xs-6 col-sm-6 col-md-2">
                                <a href="@Url.Action("MagazineThree", "Magazine")">
                                    <img class="img-responsive" src="~/plugins/pages/img/news/5.jpg" alt="sara starts its journey in dhaka" />
                                    <div class="demo-gallery-poster">
                                        <img src="/plugins/pages/img/news/zoom.png" class="img-responsive hidden-xs" alt="sara starts its journey in dhaka" />
                                    </div>
                                </a>
                            </li>

                            <li class="col-xs-6 col-sm-6 col-md-2">
                                <a href="@Url.Action("MagazineFour", "Magazine")">
                                    <img class="img-responsive" src="~/plugins/pages/img/news/2.jpg" alt="sara starts its journey in dhaka" />
                                    <div class="demo-gallery-poster">
                                        <img src="/plugins/pages/img/news/zoom.png" class="img-responsive hidden-xs" alt="sara starts its journey in dhaka" />
                                    </div>
                                </a>
                            </li>

                            <li class="col-xs-6 col-sm-6 col-md-2">
                                <a href="@Url.Action("MagazineFive", "Magazine")">
                                    <img class="img-responsive magazine" src="~/plugins/pages/img/news/7.jpg" alt="sara starts its journey in dhaka" style="height:85px !important;" />
                                    <div class="demo-gallery-poster">
                                        <img src="/plugins/pages/img/news/zoom.png" class="img-responsive hidden-xs" alt="sara starts its journey in dhaka" />
                                    </div>
                                </a>
                            </li>
                            
                            <li class="col-xs-6 col-sm-6 col-md-2">
                                <a href="@Url.Action("MagazineSix", "Magazine")">
                                    <img class="img-responsive magazine" src="~/plugins/pages/img/news/9.jpg" alt="sara starts its journey in dhaka" style="height:85px !important;" title="Opening ceremony at uttara outlet"/>
                                    <div class="demo-gallery-poster">
                                        <img src="/plugins/pages/img/news/zoom.png" class="img-responsive hidden-xs" alt="sara starts its journey in dhaka" />
                                    </div>
                                </a>
                            </li>







                        </ul>
                    </div>

                </div>
            </div>



        </div>
        <!-- END CONTENT -->









    </div>
</div>


<!--Script For News Event Sidebar Menus-->
<script type="text/javascript">
    jQuery(document).ready(function () {
        //Layout.init();
        //Layout.initOWL();
        //Layout.initTwitter();


        // jQury for right side content //

        //$('.list-group a:first').addClass('active');
        $('.news-content-page:not(:first)').hide();
        $('.news-menu a').click(function (event) {
            event.preventDefault();
            var content = $(this).attr('href');
            $(this).parent().addClass('active');
            $(this).parent().siblings().removeClass('active');
            $(content).show();
            $(content).siblings('.news-content-page').hide();
        });


        // End jQury for right side content //



    });


    // Magazine Photo Gallery
    //$(document).ready(function () {
    //    $('#lightgallery').lightGallery();
    //});

</script>


<!--End Script For News Event Sidebar Menus-->